name: docs

on:
  workflow_dispatch:
  push:
    branches: [ 'docs*' ]
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.x
      - name: Generate cmd docs
        run: make prep-docs
      - name: Run mkdocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: timoni.sh
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: hack/mkdocs/requirements.txt
